### ISSUE TITLE
Can you share the network structure?

### ISSUE THREAD

**Issue by lauraset** [sudipansaha/dcvaVHROptical#10]
Hello, @sudipansaha . Your method shows promising results and inspired me a lot. However, the layer combination (2,5,8) used in your code seems different from the setting (28,16,11,6) in your paper. Can you share the network structure in this code? Thank you very much.

**Comment by sudipansaha** [comment]
Hi,

As already mentioned in the github description "Please note the method is not an exact replication of the abovementioned paper. The original code was implemented in Matlab and is not maintained/distributed anymore."

The network structure in this version can be found in networksForFeatureExtraction.py

Original code in the paper was based on a Matlab/MatConvNet, which I stopped using just a while after the publication of the original paper. This network was used in that: https://sites.google.com/site/michelevolpiresearch/codes/dense-labeling

DCVA is a general framework which can be adopted for different architectures with a little effort. The layers for feature extraction would change when a different network is used.

Hope it clarifies your question.

**Comment by lauraset** [comment]
Hi, @sudipansaha . Thank you very much. I got it.
